library(shiny)
setwd("~/GitHub/AgenteViajeroColombia/data")
if (!exists("all_cities")) all_cities = readRDS("cities.rds")
if (!exists("usa_cities")) usa_cities = readRDS("usa_cities.rds")
if (!exists("distance_matrix")) distance_matrix = readRDS("distance_matrix.rds")
if (!exists("great_circles")) great_circles = readRDS("great_circles.rds")
if (!exists("DistanciasEntreCiudades")) DistanciasEntreCiudades = readRDS("DistanciasEntreCiudades.rds")
ciudadesDeColombia <- read.csv("ciudadesDeColombia.csv",header=T, sep = ";")
DistanciasEntreCiudades <- read.csv("DistanciasEntreCiudades.csv",header=T, sep = ";")